### ISSUE TITLE
Unable to find previous versions

### ISSUE THREAD

**Issue by balaji-b-v** [JamesHemery/gulp-append-prepend#11]
since your update on April 1 2019, the yarn package manager hasnt been able to find earlier versions:
eg: yarn install gulp-append-prepend@1.0.4 fails

Please look if you can make available the earlier versions keeping in view the backward compatibility.

Thanks in advance, JamesHemery.

**Comment by JamesHemery** [comment]
When i try to install gulp-append-prepend@1.0.4 with yarn, it's work. Can you send a screenshot of the error ?

Thanks,

**Comment by balaji-b-v** [comment]
please find the codeship build SS.

![yarnBuildError](https://user-images.githubusercontent.com/3445541/55552976-93a01500-56fc-11e9-8dc4-243ea789cf84.png)

**Comment by JamesHemery** [comment]
@balaji-b-v Can you share your package.json ? Because on my side versions 1.0.4, 1.0.5, 1.0.6 work properly. Did you try to empty the npm / yarn cache?

**Comment by balaji-b-v** [comment]
just the deps and dev deps of my package.json.
Also note am using yarn packagemanager for installs via a custom npm  helper https://www.npmjs.com/package/mm-wiredep-away

`"dependencies": {
    "@bower_components/a0-angular-storage": "auth0/angular-storage#^0.0.15",
    "@bower_components/angular": "angular/bower-angular#1.5.7",
    "@bower_components/angular-animate": "angular/bower-angular-animate#1.5.7",
    "@bower_components/angular-aria": "angular/bower-angular-aria#1.5.7",
    "@bower_components/angular-cache-buster": "saintmac/angular-cache-buster#^0.4.3",
    "@bower_components/angular-cookies": "angular/bower-angular-cookies#1.5.7",
    "@bower_components/angular-material": "angular/bower-material#1.1.1",
    "@bower_components/angular-material-data-table": "daniel-nagy/md-data-table#^0.10.9",
    "@bower_components/angular-messages": "angular/bower-angular-messages#1.5.7",
    "@bower_components/angular-mocks": "angular/bower-angular-mocks#1.5.7",
    "@bower_components/angular-permission": "Narzerus/angular-permission#^4.0.6",
    "@bower_components/angular-resource": "angular/bower-angular-resource#1.5.7",
    "@bower_components/angular-sanitize": "angular/bower-angular-sanitize#1.5.7",
    "@bower_components/angular-translate": "PascalPrecht/bower-angular-translate#2.11.0",
    "@bower_components/angular-translate-loader-partial": "PascalPrecht/bower-angular-translate-loader-partial#2.11.0",
    "@bower_components/angular-ui-router": "angular-ui/angular-ui-router-bower#^0.2.8",
    "@bower_components/angular-uuid": "ajsd/angular-uuid#^0.1.0",
    "@bower_components/api-check": "kentcdodds/apiCheck.js#7.0.0",
    "@bower_components/bardjs": "wardbell/bardjs#^0.1.10",
    "@bower_components/bower": "theshock/atomjs#*",
    "@bower_components/install": "tombigel/detect-zoom#^1.0.4",
    "@bower_components/jquery": "jquery/jquery-dist#2.2.4",
    "@bower_components/mm-dynamic-forms": "balaji-b-v/mm-dynamic-forms#^0.0.6",
    "@bower_components/mobile-detect": "hgoebl/mobile-detect.js#1.3.2",
    "@bower_components/moment": "moment/moment#2.13.0",
    "@bower_components/ng-csv": "asafdav/ng-csv#^0.3.6",
    "@bower_components/ng-file-upload": "danialfarid/angular-file-upload-bower#^12.2.13",
    "@bower_components/ng-idle": "HackedByChinese/ng-idle#^1.2.2",
    "@bower_components/ng-jsonpath": "noherczeg/ng-jsonpath#^0.1.3",
    "@bower_components/ngDropover": "Verical/ngDropover#^1.1.4",
    "@bower_components/ngprogress": "VictorBjelkholm/ngProgress#^1.1.3",
    "@bower_components/perfect-scrollbar": "noraesae/perfect-scrollbar-bower#0.6.11",
    "@bower_components/sinon": "cjohansen/Sinon.JS#1.15.4",
    "@bower_components/ui-router-extras": "christopherthielen/ui-router-extras#^0.1.3",
    "@bower_components/v-accordion": "LukaszWatroba/v-accordion#^1.6.0",
    "JSON": "^1.0.0",
    "JSONPath": "^0.11.2",
    "mm-wiredep-away": "^0.0.3",
    "exec": "^0.2.1",
    "gulp-ejs": "^2.2.1",
    "gulp-ng-constant": "^1.1.0",
    "object-keys": "^1.0.11",
    "osenv": "^0.1.4",
    "read-file": "^0.2.0",
    "through2": "^2.0.3",
    "yargs": "^6.4.0"
  },
.
.
  "devDependencies": {
    "browser-sync": "~2.9.11",
    "browser-sync-spa": "~1.0.3",
    "chalk": "~1.1.1",
    "concat-stream": "^1.6.0",
    "del": "~2.0.2",
    "eslint-plugin-angular": "~0.12.0",
    "estraverse": "~4.1.0",
    "generator-material-app": "^0.2.2",
    "gulp": "^3.9.1",
    "gulp-angular-filesort": "~1.1.1",
    "gulp-angular-order": "^1.1.0",
    "gulp-angular-templatecache": "~1.8.0",
    "gulp-append-prepend": "^1.0.4",
    "gulp-autoprefixer": "~3.0.2",
    "gulp-cache-bust": "^1.3.0",
    "gulp-clean-css": "^2.0.3",
    "gulp-concat": "^2.6.1",
    "gulp-cssnano": "~2.1.0",
    "gulp-eslint": "~1.0.0",
    "gulp-filter": "~3.0.1",
    "gulp-flatten": "~0.2.0",
    "gulp-htmlmin": "~1.3.0",
    "gulp-inject": "~3.0.0",
    "gulp-json-validator": "^1.1.1",
    "gulp-load-plugins": "~0.10.0",
    "gulp-ng-annotate": "~1.1.0",
    "gulp-ng-config": "^1.4.0",
    "gulp-protractor": "~1.0.0",
    "gulp-rename": "~1.2.2",
    "gulp-replace": "~0.5.4",
    "gulp-rev": "~6.0.1",
    "gulp-rev-replace": "~0.4.2",
    "gulp-rimraf": "^0.2.1",
    "gulp-sass": "~2.1.1",
    "gulp-size": "~2.0.0",
    "gulp-sourcemaps": "~1.6.0",
    "gulp-uglify": "~1.4.1",
    "gulp-useref": "~3.0.5",
    "gulp-util": "~3.0.6",
    "http-proxy-middleware": "~0.9.0",
    "istanbul": "^0.4.5",
    "karma": "~0.13.10",
    "karma-angular-filesort": "~1.0.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage": "~0.5.2",
    "karma-jasmine": "~0.3.6",
    "karma-ng-html2js-preprocessor": "~0.2.0",
    "karma-phantomjs-launcher": "~1.0.0",
    "karma-sinon": "^1.0.5",
    "karma-spec-reporter": "0.0.31",
    "lodash": "~3.10.1",
    "main-bower-files": "~2.9.0",
    "uglify-save-license": "~0.4.1",
    "wrench": "~1.5.8"
  },`

**Comment by JamesHemery** [comment]
It's very strange, did you try to empty the npm / yarn cache?

**Comment by balaji-b-v** [comment]
yes codehsip > reset cache > restart build was attempted

**Comment by JamesHemery** [comment]
Did you try to upgrade to 1.0.7? The update has no major changes.

**Comment by balaji-b-v** [comment]
i did try:
round 1: "gulp-append-prepend": "^1.0.4" which pulled the latest v1.0.7
round 2: then tried   "gulp-append-prepend": "#1.0.4" to pull a specific older version
round 3: "gulp-append-prepend": "#1.0.6"

still was facing the same error

**Comment by JamesHemery** [comment]
I do not find the source of the problem, can you try to replace the dependency by this: `"gulp-append-prepend": "jameshemery/gulp-append-prepend#master"` ? 

With this, yarn/npm will not try to retrieve the package on the npm repository but directly on the master branch of the github repository.

**Comment by balaji-b-v** [comment]
Does your new changes on master require node >= 8.x version?

as i can see: 
 "engines": {
    "node": ">=8.15.0"
  },

this is another finding : as am using this for angular 1.5.7 based app that uses node version <= 6

Is it possible to allow something like
 "engines": {
    "node": ">=4.2.3"
  },

unless you have a hard dependency on newer node version.

**Comment by JamesHemery** [comment]
@balaji-b-v I made an update to support node >= 4. Can you try to use latest published version ? 
`"gulp-append-prepend": "^1.0.8"`
