### ISSUE TITLE
Error: Cannot find module 'plugin-error'

### ISSUE THREAD

**Issue by andreysavihin** [JamesHemery/gulp-append-prepend#7]
Please add "plugin-error":"^1.0.1" to dependencies
https://github.com/JamesHemery/gulp-append-prepend/blob/master/index.js#L3

**Comment by JamesHemery** [comment]
PR #8 merged. Thanks you.

**Comment by VladimirIvanin** [comment]
Please publish a new version in npm

**Comment by JamesHemery** [comment]
It's good !
